[info]
author = "AVE"
description = "检测 Internet Explorer 4.x/5.x Scriptlet ActiveX 控件任意文件读取漏洞"
id = "POC-AVE-2000-0915"
name = "CVE-2000-0767 PoC"
severity = "low"
tags = ["cve-2000-0767"]
vuln_id = [
    "CVE-2000-0767",
    "AVE-2000-0915",
]

[poc]
logic = "all"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/"
protocol = "http"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = ["Scriptlet Rendering"]
