[info]
author = "ave"
description = "AVE-2000-1668 verification"
id = "POC-AVE-2000-1668"
name = "PoC for AVE-2000-1668"
severity = "medium"
tags = ["ave-2000-1668"]
vuln_id = ["AVE-2000-1668"]

[poc]
logic = "any"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/servlet/com.sun.server.http.pagecompile.jsp92.JspServlet"
protocol = "http"

[poc.requests.headers]
User-Agent = "AVE/1.0"

[[poc.requests.matchers]]
expect = true
status = [
    200,
    302,
    500,
]
type = "status"
