[info]
author = "AVE"
description = "验证 Internet Explorer 4.x/5.x 中 Scriptlet ActiveX 控件（CLSID:06290BD4-48AA-11D2-8432-006008C3FBFC）可渲染非 HTML 文件类型，导致攻击者可读取本地任意文件"
id = "POC-AVE-2000-0915"
name = "Microsoft Internet Explorer Scriptlet Rendering Arbitrary File Read PoC"
severity = "medium"
tags = ["ave-2000-0915"]
vuln_id = [
    "CVE-2000-0767",
    "AVE-2000-0915",
]

[poc]
logic = "all"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/"
protocol = "http"

[poc.requests.body]
content = ""
type = "raw"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = [
    "Scriptlet",
    "CLSID:06290BD4",
]
