[info]
author = "ave"
description = "通过检查 QNX 系统密码文件 /etc/shadow 是否存在，并结合 QNX crypt() 算法的逆向工程，验证系统是否使用了弱加密算法。公开的利用代码可完全逆向恢复密码明文。"
id = "POC-AVE-2000-0226"
name = "QNX crypt() 弱加密本地密码恢复漏洞 PoC"
severity = "high"
tags = ["ave-2000-0226"]
vuln_id = [
    "CVE-2000-0250",
    "AVE-2000-0226",
]

[poc]
logic = "all"

[[poc.requests]]
path = "/etc/shadow"
protocol = "file"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = [":"]
