[info]
author = "ave"
description = "验证 HP-UX 10.20/11.0 crontab 命令的符号链接跟踪漏洞。通过在 crontab 编辑会话期间为 /tmp 文件创建一个符号链接，待退出会话后读取 crontab 生成的错误消息，从而读取任意系统文件。"
id = "POC-AVE-2000-0703"
name = "HP-UX crontab 符号链接文件覆盖漏洞 PoC"
severity = "high"
tags = ["ave-2000-0703"]
vuln_id = [
    "CVE-2000-0972",
    "AVE-2000-0703",
]

[poc]
logic = "all"

[[poc.requests]]
path = "/etc/passwd"
protocol = "file"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = ["root:"]
