[info]
author = "ave"
description = "验证Sun Java Web Server 2.0及更早版本是否存在远程命令执行漏洞。攻击者通过board.html上传恶意Java代码后直接调用JSP编译器servlet实现RCE。本PoC检测/servlet/sunexamples.BBoardServlet路径是否存在，判断目标是否受影响。"
id = "POC-AVE-2000-0763"
name = "CVE-2000-0629 PoC"
severity = "high"
tags = ["ave-2000-0763"]
vuln_id = [
    "CVE-2000-0629",
    "AVE-2000-0763",
]

[poc]
logic = "all"

[[poc.requests]]
method = "GET"
path = "/servlet/sunexamples.BBoardServlet"
protocol = "http"

[[poc.requests.matchers]]
expect = true
part = "body"
status = [
    200,
    403,
    404,
]
type = "status"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = [
    "BBoardServlet",
    "servlet",
    "Sun",
]
