[info]
author = "ave"
description = "通过向 Microsoft Account 服务发送 HTTP 请求并检测响应中是否包含 'account' 标识，验证是否存在 Missing Authorization 导致的特权提升漏洞。"
id = "POC-AVE-2025-0858"
name = "CVE-2025-21396 Microsoft Account 特权提升漏洞 PoC"
severity = "high"
tags = ["ave-2025-0858"]
vuln_id = [
    "CVE-2025-21396",
    "AVE-2025-0858",
]

[poc]
logic = "all"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}"
protocol = "http"

[poc.requests.headers]
User-Agent = "AVE/1.0"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = ["account"]
