[basic]
description = 'tags.<value>Apple iPhone OS 的 Microsoft Exchange 支持组件存在安全绕过漏洞。在 iPhone OS 3.1 及 iPod touch 3.1.1 之前的版本中，Exchange ActiveSync 组件未正确实现"最大不活动时间锁定"功能，导致"要求输入密码"时间设置可以超过 Exchange 服务器推送的最大允许值。本地攻击者通过在设备上手动设置一个较长的 Require Passcode 时间，即可绕过 Exchange ActiveSync 策略施加的设备自动锁定限制，从而在设备闲置期间未经授权访问 Exchange 邮件、日历及其他同步数据。该漏洞利用需满足以下条件：设备已配置 Microsoft Exchange 账户并受服务器 ActiveSync 策略管理，攻击者需具备物理接触设备的权限以修改本地密码策略设置。'
published = "2009-09-10T21:30:01Z"
remediation = '将 iPhone 升级至 iOS 3.1 或更高版本，iPod touch 升级至 iOS 3.1.1 或更高版本。若暂无法升级，可在 Exchange ActiveSync 账户设置中手动缩短"Require Passcode"时间值，确保其不大于服务器设定的"Maximum inactivity time lock"值，以临时缓解绕过 Exchange 安全限制的风险。'
score = 4.6
severity = "MEDIUM"
sources = ["tenable"]
title = "Apple iPhone OS Microsoft Exchange 安全绕过漏洞"
updated = "2026-06-16T23:10:14Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2009-2794"]
ave_id = "AVE-2009-0086"

[meta]
collected_at = "2026-08-08T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://lists.apple.com/archives/security-announce/2009/Sep/msg00001.html",
    "http://secunia.com/advisories/36677",
    "http://support.apple.com/kb/HT3860",
    "http://www.securityfocus.com/bid/36342",
    "https://exchange.xforce.ibmcloud.com/vulnerabilities/53181",
    "https://github.com/CVEProject/cvelistV5/blob/8b89a27a7c0cbc0598b486c0b259a36857e7229d/cves/2009/2xxx/CVE-2009-2794.json",
    "https://github.com/LiuCan01/cve-list-pro/blob/78b55511cee3604c22d518e32822f0435d0cacc0/cve-list/CVE-2009/CVE-2009-2794",
    "https://github.com/Patrowl/PatrowlHearsData/blob/8c9d47e9557df614f7298b810b5ff61b919d2e0f/CVE/data/2009/CVE-2009-2794.json",
    "https://github.com/nomi-sec/NVD-Database/blob/23dc120c34402aaa65883c51c1d03b3cb02c20cb/2009/CVE-2009-2794.json",
    "https://github.com/opencve/opencve-kb/blob/80b71cffea20d30aae183ea8e9c0be384663772e/2009/CVE-2009-2794.json",
    "https://github.com/olbat/nvdcve/blob/aea18474d4ab97b12521ebedab21d6cf4fa5e991/nvdcve/CVE-2009-2794.json",
    "https://github.com/CyberSecAI/cve_info/blob/03b7e36424574a3a9ba5fd13480a326b666a1046/2009/2xxx/CVE-2009-2794.json",
    "https://github.com/fkie-cad/nvd-json-data-feeds/blob/5365b557c2b7d7a6027d1c8153847f51b77378a1/CVE-2009/CVE-2009-27xx/CVE-2009-2794.json",
    "https://github.com/yarencheng/cve-devops-playground/blob/5d82618844b7e318810784b38748531fdfa40755/content/CVE-2009-2794.md",
    "https://github.com/CVEProject/cvelist-dev/blob/5b8fbb570438e8094550205589cc6f1d122acc94/2009/2xxx/CVE-2009-2794.json",
]
