[basic]
description = "Microsoft Internet Explorer 9至11版本及Windows Vista SP2、Windows Server 2008 SP2/R2 SP1、Windows 7 SP1中的Internet Messaging API存在信息泄漏漏洞。该漏洞源于程序对内存中对象处理不当，远程攻击者可通过诱导用户访问特制网站，利用该漏洞探测目标系统上任意文件的存在状态，导致敏感信息泄露。攻击需用户交互，CVSS评分6.5，危害等级中危。Microsoft已在安全更新3192887中修复此漏洞。"
published = "2016-10-14T02:59:13Z"
remediation = '立即安装 Microsoft 安全公告 MS16-104 提供的累积安全更新 3192887，该更新修复了 Internet Explorer 9~11 及 Windows Internet Messaging API 中的信息泄漏漏洞。可通过 Windows Update 自动获取更新，或从 Microsoft 下载中心手动下载安装。临时缓解措施：配置 Internet Explorer 将 Internet 区域安全级别设为"高"，禁用活动脚本及 ActiveX 控件。'
score = 6.5
severity = "MEDIUM"
sources = ["kev"]
title = "Microsoft Internet Explorer 及 Internet Messaging API 信息泄漏漏洞"
updated = "2026-06-17T00:45:27Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2016-3298"]
ave_id = "AVE-2016-0209"

[meta]
collected_at = "2026-07-27T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://www.securityfocus.com/bid/93392",
    "http://www.securitytracker.com/id/1036992",
    "https://docs.microsoft.com/en-us/security-updates/securitybulletins/2016/ms16-118",
    "https://docs.microsoft.com/en-us/security-updates/securitybulletins/2016/ms16-126",
    "https://www.cisa.gov/known-exploited-vulnerabilities-catalog?field_cve=CVE-2016-3298",
    "https://github.com/trickest/cve/blob/e69d88e0152845fc4d4b49970ca6e503f56b2f93/2016/CVE-2016-3298.md",
    "https://github.com/CVEProject/cvelistV5/blob/50b2026c1039c6a81b95d80535c772b9d8685178/cves/2016/3xxx/CVE-2016-3298.json",
    "https://github.com/LiuCan01/cve-list-pro/blob/78b55511cee3604c22d518e32822f0435d0cacc0/cve-list/CVE-2016/CVE-2016-3298",
    "https://github.com/eyalmazuz/ThreatIntelligenceCorpus/blob/c47f9d2b7ba92e0cbba71c67b938a49e055c5cdc/Corpus/microsoft-patches-CVE-2016-3298-second-information-disclosure-zero-day.txt",
    "https://github.com/cisagov/vulnrichment/blob/d2b9f82473296f370428cbc110ec5b988e3fd692/2016/3xxx/CVE-2016-3298.json",
    "https://github.com/ctxis/CAPE/blob/dae9fa6a254ecdbabeb7eb0d2389fa63722c1e82/data/yara/memory/cve_2016_3298.yar",
    "https://github.com/a-dhaou-tekup/VRA/blob/3e4f21c329250c5eca327489d3fd5be9b398ce7b/data/rag_corpus/cisa_kev_notes/CVE-2016-3298.txt",
    "https://github.com/Ebiquity/CASIE/blob/2c8beef56d48e8de6599891c6a5e0e5f0d82e20c/data/source/267.txt",
    "https://github.com/Ostorlab/KEV/blob/8feadeb8b7ff54359eab87941769781629146b23/README.md",
    "https://github.com/lucacapacci/cisa_kev/blob/63008d9134e74f63e93e48616bac78e5f7abdf5b/data_single/2016/CVE-2016-3298.csv",
]
