[basic]
description = "GHSA-h4g2-xfmw-q2c9是一个安全漏洞，影响相关产品的安全性。攻击者可能利用此漏洞执行任意代码或获取未授权访问。建议用户及时更新到最新版本以修复此问题。"
published = ""
remediation = "请参考官方安全公告，及时安装安全更新或升级到最新版本。"
score = 5
severity = "MEDIUM"
sources = ["ghsa"]
title = "Clauster 仪表盘未授权访问漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["GHSA-h4g2-xfmw-q2c9"]
ave_id = "AVE-2026-1117"

[meta]
collected_at = "2026-08-06T05:07:03.210428154+00:00"
status = "completed"

[references]
urls = []
