[basic]
description = "tags.<value>Webmin 0.92 及更早版本的 Web 界面在向用户展示文件内容时，未能正确引用或过滤其中的脚本代码，导致存储型跨站脚本（XSS）漏洞。经过身份验证的本地攻击者可在受影响的系统文件（如 passwd 文件中的用户名字段）中注入恶意脚本，当管理员通过 Web 界面查看该文件时，脚本将在浏览器中执行，从而窃取会话 Cookie 或执行其他恶意操作。该漏洞影响 Webmin 0.92 及更早版本。"
published = "2002-12-31T05:00:00.000"
remediation = "立即升级 Webmin 到 ≥1.990 版本（包含安全修复程序），启用输入验证功能 `input_filter` 并设置 `session_cookie_secure=1`，同时在 Web应用层添加 CSRF 令牌验证，以防止用户在密码文件等字段中提交恶意脚本代码。"
score = 3.6
severity = "LOW"
sources = ["exploitdb"]
title = "Webmin 0.x Web Interface 跨站脚本攻击漏洞"
updated = "2026-06-16T21:59:45.880"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2002-1673"]
ave_id = "AVE-2002-0652"

[meta]
collected_at = "2026-08-06T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://online.securityfocus.com/archive/1/263181",
    "http://www.securityfocus.com/bid/4329",
    "https://exchange.xforce.ibmcloud.com/vulnerabilities/8596",
    "https://www.exploit-db.com/exploits/21348",
    "https://github.com/CVEProject/cvelistV5/blob/316b61870d1ace84a248a4e6c4f8802fe9d4e563/cves/2002/1xxx/CVE-2002-1673.json",
    "https://github.com/LiuCan01/cve-list-pro/blob/78b55511cee3604c22d518e32822f0435d0cacc0/cve-list/CVE-2002/CVE-2002-1673",
    "https://github.com/Patrowl/PatrowlHearsData/blob/52f0c58efa9b550b12cbc3a2cc567bbc12de27a9/CVE/data/2002/CVE-2002-1673.json",
    "https://github.com/nomi-sec/NVD-Database/blob/23dc120c34402aaa65883c51c1d03b3cb02c20cb/2002/CVE-2002-1673.json",
    "https://github.com/HORKimhab/poc-cve-collection/blob/dde218104d183b4531b1e275856d67b12288f14d/2002/1xxx/CVE-2002-1673.md",
    "https://github.com/opencve/opencve-kb/blob/238e25b4e348c510d4ca1468e43eb6a7b196ac22/2002/CVE-2002-1673.json",
    "https://github.com/olbat/nvdcve/blob/336c506d8c2ab5b6ec8e55edc2021c49b3be8e2c/nvdcve/CVE-2002-1673.json",
    "https://github.com/aquasecurity/vuln-list-debian/blob/0274e3152f045058fa5c33f6d602778b76d936e8/tracker/CVE/2002/CVE-2002-1673.json",
    "https://github.com/CyberSecAI/cve_info/blob/03b7e36424574a3a9ba5fd13480a326b666a1046/2002/1xxx/CVE-2002-1673.json",
    "https://github.com/CVEProject/cvelist-dev/blob/5b8fbb570438e8094550205589cc6f1d122acc94/2002/1xxx/CVE-2002-1673.json",
]
