[basic]
description = "CVE-2019-1898是一个安全漏洞，影响相关产品的安全性。攻击者可能利用此漏洞执行任意代码或获取未授权访问。建议用户及时更新到最新版本以修复此问题。"
published = "2019-06-20T03:15:12.433"
remediation = "立即升级受影响设备固件至指定版本：RV110W升级到1.2.2.4及以上，RV130W升级到1.0.3.51及以上，RV215W升级到1.3.1.4及以上。如无法立即升级，建议通过防火墙封锁对HTTP端口的访问，并关闭不必要的服务以减少攻击面。"
score = 5.3
severity = "MEDIUM"
sources = ["nuclei"]
title = "Cisco RV110W 路由器 未授权访问漏洞"
updated = "2026-06-17T02:29:33.650"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2019-1898"]
ave_id = "AVE-2019-0141"

[meta]
collected_at = "2026-08-06T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://www.securityfocus.com/bid/108865",
    "https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-20190619-rv-fileaccess",
    "https://www.tenable.com/security/research/tra-2019-29",
    "https://github.com/projectdiscovery/nuclei-templates/blob/main/http/cves/2019/CVE-2019-1898.yaml",
    "https://github.com/trickest/cve/blob/15eaa178baaf955987a866a2c9d91dc02a2fb4aa/2019/CVE-2019-1898.md",
    "https://github.com/ExpLangcn/NucleiTP/blob/2b7ecb9031a6eda4f272793045f29b339d8e0cce/CVES/medium/CVE-2019-1898.yaml",
    "https://github.com/CVEDB/Poc-Git/blob/0275aeb329b0747c9a1d46160c921eae06095557/2019/CVE-2019-1898.md",
    "https://github.com/kaismax/CVE-Poc/blob/6d8c93dabf674cea102713781cc534d577412357/2019/CVE-2019-1898.md",
    "https://github.com/trickest/cve/blob/15eaa178baaf955987a866a2c9d91dc02a2fb4aa/2019/CVE-2019-18988.md",
    "https://github.com/trickest/cve/blob/15eaa178baaf955987a866a2c9d91dc02a2fb4aa/2019/CVE-2019-18989.md",
    "https://github.com/trickest/cve/blob/15eaa178baaf955987a866a2c9d91dc02a2fb4aa/2019/CVE-2019-18980.md",
    "https://github.com/ARPSyndicate/suricata-vedas/blob/fe24794ad36564b5bbc7c69101525011387b8650/2019/CVE-2019-1898.rules",
    "https://github.com/mabitoski/cve_submodules/blob/44ad7e2705b3aef1b2ffaf64bd47596c10a6c2e4/2019/CVE-2019-1898.md",
    "https://github.com/nomi-sec/NVD-Database/blob/23dc120c34402aaa65883c51c1d03b3cb02c20cb/2019/CVE-2019-1898.json",
    "https://github.com/mr-r3b00t/CVE-2019-18988",
]
