[basic]
description = "ZZZCMS 的 zzzphp V1.6.1 版本在 inc/zzz_template.php 文件中的 parserIfLabel() 函数存在代码注入漏洞，该函数对模板标签的过滤不够严格，攻击者可通过构造包含 if:assert 子串的恶意输入，绕过安全验证并在服务器端执行任意 PHP 代码，最终导致远程代码执行。该漏洞影响使用 ZZZCMS 搭建的网站系统，攻击者需要具备后台管理权限或能够向系统提交模板内容才能触发漏洞利用。"
published = "2019-02-23T18:29:00Z"
remediation = "建议将 ZZZCMS zzzphp 升级至最新安全版本。若无法升级，可通过修改 `inc/zzz_template.php` 文件，在 `parserIfLabel()` 函数中增加对 `assert`、`eval` 等危险关键字的严格过滤，或在 Web 应用防火墙 (WAF) 上拦截包含 `if:assert` 等特征的恶意请求。"
score = 7.2
severity = "HIGH"
sources = ["nuclei"]
title = "ZZZCMS zzzphp 远程代码执行漏洞"
updated = "2026-06-17T02:42:58Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2019-9041"]
ave_id = "AVE-2019-0211"

[meta]
collected_at = "2026-08-07T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://www.iwantacve.cn/index.php/archives/118/",
    "https://www.exploit-db.com/exploits/46454/",
    "https://www.exploit-db.com/exploits/46454",
    "https://github.com/projectdiscovery/nuclei-templates/blob/main/http/cves/2019/CVE-2019-9041.yaml",
    "https://github.com/trickest/cve/blob/8c4eb2837c857f4cda9b4ed4ab227a0668647438/2019/CVE-2019-9041.md",
    "https://github.com/projectdiscovery/nuclei-templates/blob/a59bc25d9f5ca1e2e0b6dfb956fc7eb7fed93b96/http/cves/2019/CVE-2019-9041.yaml",
    "https://github.com/ExpLangcn/NucleiTP/blob/2b7ecb9031a6eda4f272793045f29b339d8e0cce/CVES/high/CVE-2019-9041.yaml",
    "https://github.com/ExpLangcn/NucleiTP/blob/2b7ecb9031a6eda4f272793045f29b339d8e0cce/CVES/high/cve-2019-9041-4291.yaml",
    "https://github.com/ExpLangcn/NucleiTP/blob/2b7ecb9031a6eda4f272793045f29b339d8e0cce/CVES/high/cve-2019-9041-4288.yaml",
    "https://github.com/ExpLangcn/NucleiTP/blob/2b7ecb9031a6eda4f272793045f29b339d8e0cce/CVES/high/cve-2019-9041-4289.yaml",
    "https://github.com/ExpLangcn/NucleiTP/blob/2b7ecb9031a6eda4f272793045f29b339d8e0cce/CVES/high/cve-2019-9041-4290.yaml",
    "https://github.com/ExpLangcn/NucleiTP/blob/2b7ecb9031a6eda4f272793045f29b339d8e0cce/CVES/high/cve-2019-9041-4286.yaml",
    "https://github.com/GhostTroops/scan4all/blob/fff03b51bf79c8993a46c1da766ec993e1102c47/config/51pwn/yaml/ZZZPHP/CVE-2019-9041.yaml",
    "https://github.com/GhostTroops/scan4all/blob/fff03b51bf79c8993a46c1da766ec993e1102c47/config/51pwn/TPALL/cves/2019/CVE-2019-9041.yaml",
]
