[basic]
description = "Sitecore CMS 7.0 至 7.2 及 Sitecore XP 7.5 至 8.2 版本的 Security.AntiCSRF 模块中存在 .NET 反序列化漏洞。未经身份认证的远程攻击者可通过向目标系统发送特制的 HTTP POST 请求，在 __CSRFTOKEN 参数中携带恶意的序列化 .NET 对象触发该漏洞，导致远程代码执行。攻击者无需任何认证即可利用，危害严重，CVSS 评分 9.8。"
published = "2019-05-31T21:29:06Z"
remediation = "升级 Sitecore XP 至 8.2 Update-1 或更高版本（8.2 Update-7 为推荐稳定版），或升级 Sitecore CMS 至 8.2 Update-1 及以上版本。该漏洞通过 HTTP POST 参数 __CSRFTOKEN 传递序列化 .NET 对象触发，如无法立即升级，可在反向代理或 WAF 层面拦截包含 __CSRFTOKEN 参数的外部请求作为临时缓解措施。"
score = 9.8
severity = "CRITICAL"
sources = ["kev"]
title = "Sitecore CMS和Sitecore XP 反序列化远程代码执行漏洞"
updated = "2026-06-17T02:44:46Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2019-9874"]
ave_id = "AVE-2019-1685"

[meta]
collected_at = "2026-08-03T00:00:00Z"
status = "completed"

[references]
urls = [
    "https://dev.sitecore.net/Downloads.aspx",
    "https://www.synacktiv.com/blog.html",
    "https://www.synacktiv.com/ressources/advisories/Sitecore_CSRF_deserialize_RCE.pdf",
    "https://www.cisa.gov/known-exploited-vulnerabilities-catalog?field_cve=CVE-2019-9874",
    "https://github.com/projectdiscovery/nuclei-templates/blob/main/http/cves/2019/CVE-2019-9874.yaml",
    "https://github.com/trickest/cve/blob/7d40e7d94b41c478b4d1a654c7bc3bcf34fa7beb/2019/CVE-2019-9874.md",
    "https://github.com/0xMarcio/cve/blob/0cbbfd20018b392e9b69a82c4ac1297203bfeefd/2019/CVE-2019-9874.md",
    "https://github.com/projectdiscovery/nuclei-templates/blob/e9f0fe7fa4f5c548bbd1a4d3b65d0f181021e664/http/cves/2019/CVE-2019-9874.yaml",
    "https://github.com/CVEProject/cvelistV5/blob/8491df4167cab37455be87043bbd4187ade74c40/cves/2019/9xxx/CVE-2019-9874.json",
    "https://github.com/cisagov/vulnrichment/blob/6ff73fb4bb99974a2b535c179f337dd820550366/2019/9xxx/CVE-2019-9874.json",
    "https://github.com/0x727/FingerprintHub/blob/5784554659c9500df8525e8db4f986630a56d8a1/plugins/sitecore/experience_platform/CVE-2019-9874.yaml",
    "https://github.com/Patrowl/PatrowlHearsData/blob/16f8cf2a3c129bb57f3727599f3730e6001c1186/CVE/data/2019/CVE-2019-9874.json",
    "https://github.com/Patrowl/PatrowlHearsData/blob/16f8cf2a3c129bb57f3727599f3730e6001c1186/SSVC/data/2019/CVE-2019-9874.json",
    "https://github.com/ARPSyndicate/suricata-vedas/blob/fe24794ad36564b5bbc7c69101525011387b8650/2019/CVE-2019-9874.rules",
    "https://github.com/youki992/VscanPlus/blob/714a0e276a538a22c1a6215c71458a8b59a920ef/pocs_yml/nucleiFiles/http/cves/2019/CVE-2019-9874.yaml",
]
