[basic]
description = 'IBM Planning Analytics 2.0.0 至 2.0.8 版本存在配置覆盖漏洞，攻击者无需身份认证即可通过特制请求覆盖管理员配置，以 "admin" 用户身份登录系统，进而利用 TM1 脚本功能以 root 或 SYSTEM 权限执行任意代码。该漏洞影响 IBM Planning Analytics 2.0.0-2.0.8 所有版本，CVSS 3.1 评分 9.8（严重），攻击向量为网络远程、攻击复杂度低、无需权限与用户交互。攻击者仅需向目标服务发送恶意配置请求即可触发，成功利用可导致服务器完全沦陷。IBM 已发布安全补丁修复此漏洞，建议尽快升级至 2.0.9 或更高版本。'
published = "2019-12-18T17:16:43Z"
remediation = "立即升级到 IBM Planning Analytics 2.0.9 及以上版本，这是根本解决方法。升级前，可临时通过修改防火墙规则禁止访问 TM1 管理端口 5498/5495的非管理流量，或将 Admin 服务器从互联网直接暴露移除至内部网络作为紧急缓解措施。若无法立即升级，建议禁用所有未使用的服务和端口，并限制admin账户仅本地登录。"
score = 9.8
severity = "CRITICAL"
sources = ["kev"]
title = "IBM Planning Analytics 未认证远程代码执行漏洞"
updated = "2026-06-17T02:36:50Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2019-4716"]
ave_id = "AVE-2019-1300"

[meta]
collected_at = "2026-08-03T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://packetstormsecurity.com/files/156953/IBM-Cognos-TM1-IBM-Planning-Analytics-Server-Configuration-Overwrite-Code-Execution.html",
    "http://seclists.org/fulldisclosure/2020/Mar/44",
    "https://exchange.xforce.ibmcloud.com/vulnerabilities/172094",
    "https://www.ibm.com/support/pages/node/1127781",
    "https://www.cisa.gov/known-exploited-vulnerabilities-catalog?field_cve=CVE-2019-4716",
    "https://www.exploit-db.com/exploits/48273",
    "https://github.com/projectdiscovery/nuclei-templates/blob/main/http/cves/2019/CVE-2019-4716.yaml",
    "https://github.com/trickest/cve/blob/7d40e7d94b41c478b4d1a654c7bc3bcf34fa7beb/2019/CVE-2019-4716.md",
    "https://github.com/0xMarcio/cve/blob/986b45a0ac2dd215b3a5515fba0cebac769043dd/2019/CVE-2019-4716.md",
    "https://github.com/cisagov/vulnrichment/blob/0812ebe932b97710173c59d3d74959fb420956eb/2019/4xxx/CVE-2019-4716.json",
    "https://github.com/arschlochnop/VulnWatchdog/blob/96acb02a8d6942d7cdf496f8d887cd0035972f4b/data/by-cve/CVE-2019-4716.md",
    "https://github.com/sari3l/Poc-Monitor/blob/f793cabbd56af386bba619c0dff897c8d6cbc1f2/2019/CVE-2019-4716.json",
    "https://github.com/0x727/FingerprintHub/blob/dce139c84c439e9fc87d0eb2079ddda89aaeb75c/plugins/ibm/planning_analytics/CVE-2019-4716.yaml",
    "https://github.com/CVEDB/Poc-Git/blob/0275aeb329b0747c9a1d46160c921eae06095557/2019/CVE-2019-4716.md",
    "https://github.com/kaismax/CVE-Poc/blob/6d8c93dabf674cea102713781cc534d577412357/2019/CVE-2019-4716.md",
    "https://github.com/youki992/VscanPlus/blob/714a0e276a538a22c1a6215c71458a8b59a920ef/pocs_yml/nucleiFiles/http/cves/2019/CVE-2019-4716.yaml",
    "https://github.com/adampielak/nuclei-templates/blob/a2f3ff3fa5db5c7705ebd942909ec114df063700/nuclei-v3/C/CVE-2019-4716.yaml",
]
