[basic]
description = "CirCarLife SCADA 软件在 4.3 版本之前存在信息泄露漏洞，该漏洞属于 CWE-200 信息暴露类缺陷，攻击者无需任何身份认证或特殊权限，可通过向目标系统的 html/log 或 services/system/info.html 路径发送直接的 HTTP 请求，获取系统日志、运行状态及敏感的系统信息，包括但不限于设备凭据、配置信息等。该漏洞利用条件极低，仅需网络可达即可实施攻击，攻击者可借此进一步获取系统访问权限或执行更多攻击操作。CVSS 评分为 9.8 分（严重等级），影响范围广泛。PoC 和 EXP 已在 ExploitDB 和 Nuclei Templates 中公开，建议用户尽快升级至 4.3 及以上版本以消除该漏洞。"
published = "2018-06-22T00:29:00Z"
remediation = "建议立即升级 CirCarLife Scada 至 4.3 或以上版本。若无法立即升级，可通过防火墙或反向代理（如 Nginx/IIS）屏蔽 /html/log、/services/system/info.html 等敏感 URI 路径，限制 Scada 管理界面仅在内网访问，并启用身份认证（HTTP Basic/Digest Auth）防止未授权访问。"
score = 9.8
severity = "CRITICAL"
sources = ["nuclei"]
title = "CirCarLife SCADA 信息泄露漏洞"
updated = "2026-06-17T01:38:06Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2018-12634"]
ave_id = "AVE-2018-0072"

[meta]
collected_at = "2026-08-02T00:00:00Z"
status = "completed"

[references]
urls = [
    "https://github.com/SadFud/Exploits/tree/master/Real%20World/Suites/cir-pwn-life",
    "https://www.exploit-db.com/exploits/45384/",
    "https://www.seebug.org/vuldb/ssvid-97353",
    "https://www.exploit-db.com/exploits/45384",
    "https://github.com/projectdiscovery/nuclei-templates/blob/main/http/cves/2018/CVE-2018-12634.yaml",
    "https://github.com/trickest/cve/blob/7d40e7d94b41c478b4d1a654c7bc3bcf34fa7beb/2018/CVE-2018-12634.md",
    "https://github.com/0xMarcio/cve/blob/5ffa820afafb07e3d2a3856e2c3d1b6e11ccbbaa/2018/CVE-2018-12634.md",
    "https://github.com/projectdiscovery/nuclei-templates/blob/f5a1370a5c99053077d951ed65ac8cc8cef6e9f7/http/cves/2018/CVE-2018-12634.yaml",
    "https://github.com/ExpLangcn/NucleiTP/blob/2b7ecb9031a6eda4f272793045f29b339d8e0cce/CVES/critical/CVE-2018-12634.yaml",
    "https://github.com/ExpLangcn/NucleiTP/blob/2b7ecb9031a6eda4f272793045f29b339d8e0cce/CVES/medium/cve-2018-12634-3253.yaml",
    "https://github.com/ExpLangcn/NucleiTP/blob/2b7ecb9031a6eda4f272793045f29b339d8e0cce/CVES/medium/cve-2018-12634-3251.yaml",
    "https://github.com/ExpLangcn/NucleiTP/blob/2b7ecb9031a6eda4f272793045f29b339d8e0cce/CVES/critical/cve-2018-12634-3252.yaml",
    "https://github.com/ExpLangcn/NucleiTP/blob/2b7ecb9031a6eda4f272793045f29b339d8e0cce/CVES/critical/cve-2018-12634-3255.yaml",
    "https://github.com/ExpLangcn/NucleiTP/blob/2b7ecb9031a6eda4f272793045f29b339d8e0cce/CVES/critical/CVE-2018-12634_重复副本.yaml",
    "https://github.com/GhostTroops/scan4all/blob/fff03b51bf79c8993a46c1da766ec993e1102c47/config/51pwn/CVE-2018-12634.yaml",
]
