[basic]
description = "该漏洞属于特权提升漏洞，其核心原因在于 DirectX 图形内核（DXGKRNL）驱动程序在处理内存对象时存在不当的操作，导致内存管理失效。本地攻击者可通过运行特制的恶意应用程序，利用该驱动程序的缺陷来篡改内核内存，从而将进程权限从普通用户提升至系统级权限（SYSTEM）。该漏洞影响 Windows 10、Windows 10 Server 以及 Windows Server 2016 等多个版本。攻击者必须在目标系统上拥有低权限账户并能够执行代码方可触发。"
published = "2018-08-15T17:29:10Z"
remediation = "立即安装 Microsoft 2018 年 8 月安全更新：Windows 10 Version 1803 安装 KB4346783，Version 1709 安装 KB4346787，Version 1703 安装 KB4346785，Version 1607 及 Windows Server 2016 安装 KB4343895，或通过 Windows Update 自动更新至最新版本。如无法立即打补丁，可临时限制本地用户账户权限并禁用不必要的 DirectX 图形硬件加速功能，以降低被利用风险。"
score = 7.8
severity = "HIGH"
sources = ["kev"]
title = "Microsoft Windows DirectX 图形内核特权提升漏洞"
updated = "2026-06-17T02:04:47Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2018-8406"]
ave_id = "AVE-2018-0027"

[meta]
collected_at = "2026-07-29T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://www.securityfocus.com/bid/105012",
    "http://www.securitytracker.com/id/1041461",
    "https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2018-8406",
    "https://www.cisa.gov/known-exploited-vulnerabilities-catalog?field_cve=CVE-2018-8406",
    "https://github.com/trickest/cve/blob/b3a270a001a31742516eaea5c494f365de9d3c80/2018/CVE-2018-8406.md",
    "https://github.com/CVEProject/cvelistV5/blob/231116aa5795023b4be954f9aed84939e97cf046/cves/2018/8xxx/CVE-2018-8406.json",
    "https://github.com/cisagov/vulnrichment/blob/077172bcea3338bafb871871e211bbb7c87f3c3c/2018/8xxx/CVE-2018-8406.json",
    "https://github.com/trickest/cve/blob/b3a270a001a31742516eaea5c494f365de9d3c80/2018/CVE-2018-8405.md",
    "https://github.com/Patrowl/PatrowlHearsData/blob/15f9f7a0b2cc2a296dac75e46487bfa653db3e1b/CVE/data/2018/CVE-2018-8406.json",
    "https://github.com/Patrowl/PatrowlHearsData/blob/15f9f7a0b2cc2a296dac75e46487bfa653db3e1b/SSVC/data/2018/CVE-2018-8406.json",
    "https://github.com/nomi-sec/NVD-Database/blob/23dc120c34402aaa65883c51c1d03b3cb02c20cb/2018/CVE-2018-8406.json",
    "https://github.com/olbat/nvdcve/blob/add906b6a8ba20fd533c6fdd7f023c73e6090f3a/nvdcve/CVE-2018-8406.json",
    "https://github.com/fkie-cad/nvd-json-data-feeds/blob/1b01d01b655cac08088621898fd70278524e2f0e/CVE-2018/CVE-2018-84xx/CVE-2018-8406.json",
    "https://github.com/nailara-technologies/protocol-7/blob/2f11bc91c106aa93748d5788e09a11c404412298/data/protocols/cisa/CVE-2018-8406",
]
