[basic]
description = "Cisco IOS 和 IOS XE 软件的 Smart Install 功能存在输入验证不当漏洞。未经身份认证的远程攻击者可通过向受影响设备的 TCP 端口 4786 发送特制数据包，触发设备重载，导致拒绝服务（DoS）条件。该漏洞仅影响配置为 Smart Install 客户端的交换机，Smart Install 导演设备不受影响。Cisco 已在安全公告中修复此漏洞。"
published = "2018-03-28T22:29:00Z"
remediation = "立即升级受影响的 Cisco IOS/IOS XE 设备至 Cisco 安全公告 cisco-sa-20180328-smi 中指定的修复版本，可通过 Cisco IOS Software Checker 查询具体修复版本号。如无法立即升级且不需要 Smart Install 功能，可在全局配置模式下执行 `no vstack` 命令禁用该功能作为临时缓解措施。该漏洞已被 CISA 列入已知被利用漏洞目录，需优先处置。"
score = 7.5
severity = "HIGH"
sources = ["kev"]
title = "Cisco IOS/IOS XE Smart Install 拒绝服务漏洞"
updated = "2026-06-17T01:29:57Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2018-0156"]
ave_id = "AVE-2018-0006"

[meta]
collected_at = "2026-07-27T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://www.securityfocus.com/bid/103569",
    "http://www.securitytracker.com/id/1040596",
    "https://ics-cert.us-cert.gov/advisories/ICSA-18-107-04",
    "https://ics-cert.us-cert.gov/advisories/ICSA-18-107-05",
    "https://tools.cisco.com/security/center/content/CiscoSecurityAdvisory/cisco-sa-20180328-smi",
    "https://www.cisa.gov/known-exploited-vulnerabilities-catalog?field_cve=CVE-2018-0156",
    "https://github.com/trickest/cve/blob/be44b05b9428dc18bc0705cf60dd8d8640cd49b1/2018/CVE-2018-0156.md",
    "https://github.com/CVEProject/cvelistV5/blob/487ea3f21ed49470634e758e1f8f2ac74b64d6b0/cves/2018/0xxx/CVE-2018-0156.json",
    "https://github.com/cisagov/vulnrichment/blob/0d5eda5cdae3f3a50b92fdfcae2f5983174f2a99/2018/0xxx/CVE-2018-0156.json",
    "https://github.com/Patrowl/PatrowlHearsData/blob/6052148b71cb79d42fd4a59f87982387b0487834/SSVC/data/2018/CVE-2018-0156.json",
    "https://github.com/LiuCan01/cve-list-pro/blob/78b55511cee3604c22d518e32822f0435d0cacc0/cve-list/CVE-2018/CVE-2018-0156",
    "https://github.com/mabitoski/cve_submodules/blob/44ad7e2705b3aef1b2ffaf64bd47596c10a6c2e4/2018/CVE-2018-0156.md",
    "https://github.com/Ch4120N/Ch4120N-CVE-Pulse/blob/91ab7783643591e4c1949aca858fc331aabcb87c/CVEs/2018/CVE-2018-0156.md",
    "https://github.com/Patrowl/PatrowlHearsData/blob/6052148b71cb79d42fd4a59f87982387b0487834/CVE/data/2018/CVE-2018-0156.json",
    "https://github.com/brenonevs/prs-pentest/blob/001cf17eedeb4aad73618d3140ca1f5dc93e69b3/CVEs & POCs/2018/CVE-2018-0156.md",
    "https://github.com/KaweGG/vulnerability_tracker/blob/01de5763b71f6c005791d4aa8121132990782604/cves/CVE-2018-0156.md",
]
