[info]
author = "AVE"
description = "检测目标系统上是否存在 Berkeley Parallel Make (pmake) 2.1.33 及更早版本的 setuid 二进制文件。该版本存在格式化字符串漏洞，本地用户可通过在 shell 定义的 check 参数中注入格式说明符覆盖任意内存地址，导致权限提升至 root。"
id = "POC-AVE-2001-0411"
name = "SuSE Linux Berkeley Parallel Make 格式字符串漏洞 PoC"
severity = "high"
tags = ["ave-2001-0411"]
vuln_id = [
    "CVE-2001-0915",
    "AVE-2001-0411",
]

[poc]
logic = "all"

[[poc.requests]]
path = "/usr/bin/pmake"
protocol = "file"

[[poc.requests.matchers]]
expect = true
part = "body"
regex = ".+"
type = "regex"
