[info]
author = "AVE"
description = "通过DNS CHAOS类查询获取BIND版本号，检测目标BIND服务器是否为受影响版本（<4.9.8或<8.2.3），确认是否存在CVE-2001-0012信息泄漏漏洞。"
id = "POC-AVE-2001-0210"
name = "ISC BIND 敏感信息泄露漏洞 PoC"
severity = "medium"
tags = ["ave-2001-0210"]
vuln_id = [
    "CVE-2001-0012",
    "AVE-2001-0210",
]

[poc]
logic = "all"

[[poc.requests]]
dns_type = "TXT"
path = "{{Hostname}}"
protocol = "dns"

[[poc.requests.matchers]]
expect = false
part = "body"
type = "word"
words = [
    "8.2.3",
    "4.9.8",
]
