[info]
author = "ave"
description = "检测 Sambar Server 是否运行，该版本默认使用编译在二进制中的对称密钥加密密码，攻击者可利用已知密钥或修改程序副本调用解密函数破解所有用户密码"
id = "POC-AVE-2001-0459"
name = "Sambar Server 默认密码保护漏洞 PoC"
severity = "high"
tags = ["ave-2001-0459"]
vuln_id = [
    "CVE-2001-1106",
    "AVE-2001-0459",
]

[poc]
logic = "any"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/"
protocol = "http"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = [
    "Sambar Server",
    "Sambar",
]
