[info]
author = "ave"
description = "检测 APC UPS 守护进程 apcupsd 的 PID 文件是否全局可写。该漏洞允许本地攻击者修改 /var/run/apcupsd.pid 文件内容，指定任意目标进程 PID，当 apcupsd 重启或停止时会向该 PID 发送终止信号，导致目标进程被异常终止。"
id = "POC-AVE-2001-0020"
name = "APC apcupsd 本地拒绝服务 PoC"
severity = "low"
tags = ["ave-2001-0020"]
vuln_id = [
    "CVE-2001-0040",
    "AVE-2001-0020",
]

[poc]
logic = "all"

[[poc.requests]]
path = "/var/run/apcupsd.pid"
protocol = "file"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = [""]
