[info]
author = "ave"
description = "Google Chrome 18.0.1025.168 之前版本存在使用后释放漏洞，源于浏览器在处理 CSS 浮动元素时的内存管理缺陷。远程攻击者可通过构造恶意网页，诱导用户访问后触发浮动元素的异常释放与重用，导致浏览器崩溃（拒绝服务）或可能实现任意代码执行。"
id = "POC-AVE-2011-0208"
name = "CVE-2011-3081 PoC"
severity = "critical"
tags = ["ave-2011-0208"]
vuln_id = [
    "CVE-2011-3081",
    "AVE-2011-0208",
]

[poc]
logic = "all"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/poc.html"
protocol = "http"

[[poc.requests.matchers]]
expect = true
part = "body"
status = [200]
type = "status"
