[info]
author = "ave"
description = "Apple Safari 6.0 之前版本中的 WebKit 引擎存在内存破坏漏洞，攻击者可通过构造恶意网页触发该漏洞，导致远程代码执行或拒绝服务（内存损坏与应用崩溃）。该漏洞影响 Safari 浏览器及 iOS 移动操作系统，攻击条件为受害者访问包含特制内容的网页，无需身份认证即可触发。"
id = "POC-AVE-2012-0345"
name = "CVE-2012-3669 PoC"
severity = "high"
tags = ["ave-2012-0345"]
vuln_id = [
    "CVE-2012-3669",
    "AVE-2012-0345",
]

[poc]
logic = "all"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/poc.html"
protocol = "http"

[poc.requests.headers]
User-Agent = "AVE/1.0"

[[poc.requests.matchers]]
expect = true
part = "body"
status = [200]
type = "status"
