[info]
author = "ave"
description = "Apple Safari 6.0 之前的版本中，WebKit 引擎存在内存破坏漏洞。远程攻击者可通过构造恶意网站触发内存损坏，导致应用崩溃或执行任意代码。该漏洞利用条件为用户访问包含恶意内容的网页，目标系统需运行受影响版本的 Safari 浏览器。"
id = "POC-AVE-2012-0355"
name = "CVE-2012-3679 PoC"
severity = "critical"
tags = ["ave-2012-0355"]
vuln_id = [
    "CVE-2012-3679",
    "AVE-2012-0355",
]

[poc]
logic = "all"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/poc.html"
protocol = "http"

[poc.requests.headers]
User-Agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Safari/536.26"

[[poc.requests.matchers]]
expect = true
part = "body"
status = [200]
type = "status"
