[info]
author = "AVE"
description = "检测 Mozilla Firefox/Thunderbird/SeaMonkey 跨域框架导航策略绕过漏洞。通过构造包含目标子框架名称属性的表单提交目标，绕过 HTML5 框架导航策略，在跨域文档中替换任意子框架。"
id = "POC-AVE-2012-0035"
name = "CVE-2012-0445 PoC"
severity = "medium"
tags = ["cve-2012-0445"]
vuln_id = [
    "CVE-2012-0445",
    "AVE-2012-0035",
]

[poc]
logic = "all"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/poc.html"
protocol = "http"

[[poc.requests.matchers]]
expect = true
status = [200]
type = "status"
