[info]
author = "AVE"
description = "PoC/EXP for verification"
id = "POC-AVE-2002-0061"
name = "MHonArc MIME邮件头跨站脚本漏洞 PoC"
severity = "medium"
tags = ["ave-2002-0061"]
vuln_id = [
    "CVE-2002-1307",
    "AVE-2002-0061",
]

[poc]
logic = "all"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/"
protocol = "http"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = ["MHonArc"]
