[basic]
description = "Google Chrome 浏览器 17.0.963.56 之前的版本在 PDF 编解码器中存在多个整数溢出漏洞。攻击者可以通过构造包含恶意代码的特制 PDF 文件，诱导用户通过浏览器访问或打开该文件，从而触发整数溢出。该漏洞会导致浏览器进程崩溃（拒绝服务），在特定条件下甚至可能允许远程攻击者在目标系统上执行任意代码。此漏洞影响所有运行受影响版本 Chrome 的用户，攻击条件为用户触发恶意文档解析。"
published = "2012-02-16T20:55:03Z"
remediation = "建议立即将 Google Chrome 浏览器升级至 17.0.963.56 或更高版本。用户可通过浏览器的“关于 Google Chrome”页面触发自动更新机制，确保所有组件更新至最新稳定版以修复 PDF 解码器的整数溢出漏洞。"
score = 6.8
severity = "MEDIUM"
sources = ["tenable"]
title = "Google Chrome PDF解码器整数溢出漏洞"
updated = "2026-06-16T23:32:26Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2011-3015"]
ave_id = "AVE-2011-0170"

[meta]
collected_at = "2026-07-29T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://code.google.com/p/chromium/issues/detail?id=105803",
    "http://googlechromereleases.blogspot.com/2012/02/chrome-stable-update.html",
    "http://secunia.com/advisories/48016",
    "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A14690",
    "https://github.com/CVEProject/cvelistV5/blob/e75ae6c145bf0fa550455c4b2b7c9e0f03c663af/cves/2011/3xxx/CVE-2011-3015.json",
    "https://github.com/Patrowl/PatrowlHearsData/blob/e701323a68aa022329783fc6fbcb51c8037899bc/CVE/data/2011/CVE-2011-3015.json",
    "https://github.com/LiuCan01/cve-list-pro/blob/78b55511cee3604c22d518e32822f0435d0cacc0/cve-list/CVE-2011/CVE-2011-3015",
    "https://github.com/canonical/ubuntu-security-notices/blob/b9dba67c94bbc6d24eae4b34e0cd3767069dd513/osv/cve/2011/UBUNTU-CVE-2011-3015.json",
    "https://github.com/nottrobin/ubuntu-cve-tracker/blob/36e411296b5707284049ec2e0db8d2622feca498/retired/CVE-2011-3015",
    "https://github.com/canonical/ubuntu-security-notices/blob/b9dba67c94bbc6d24eae4b34e0cd3767069dd513/vex/cve/2011/CVE-2011-3015.json",
    "https://github.com/kees/ubuntu-cve-tracker/blob/66a43c37da527bc16621fb5548dca8aa1f46e537/retired/CVE-2011-3015",
    "https://github.com/nomi-sec/NVD-Database/blob/23dc120c34402aaa65883c51c1d03b3cb02c20cb/2011/CVE-2011-3015.json",
    "https://github.com/olbat/nvdcve/blob/add906b6a8ba20fd533c6fdd7f023c73e6090f3a/nvdcve/CVE-2011-3015.json",
    "https://github.com/neuvector/vul-source/blob/1f7c9527c0f5bb4cce2670b0d21c4073607d138e/ubuntu-cve-tracker/retired/CVE-2011-3015",
]
