[basic]
description = "Google Chrome的OpenType Sanitizer组件存在单字节溢出错误（off-by-one），远程攻击者可通过向目标发送特制的OpenType字体文件触发该漏洞，导致拒绝服务或可能的内存越界读取，影响Google Chrome 18.0.1025.142之前的所有版本。CWE-682（计算错误）类型的漏洞使得攻击者能够利用此缺陷造成程序不稳定或信息泄露。"
published = "2012-03-30T22:55:01Z"
remediation = "标签之间。<value>升级 Google Chrome 至 18.0.1025.142 或更高版本。如无法立即升级，可暂时避免打开来源不可信的 OpenType 字体文件，并通过浏览器设置禁用网页自定义字体渲染作为临时缓解措施。"
score = 6.8
severity = "MEDIUM"
sources = ["tenable"]
title = "Google Chrome OpenType Sanitizer单字节溢出漏洞"
updated = "2026-06-16T23:32:32Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2011-3062"]
ave_id = "AVE-2011-0196"

[meta]
collected_at = "2026-07-30T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://code.google.com/p/chromium/issues/detail?id=116524",
    "http://googlechromereleases.blogspot.com/2012/03/stable-channel-release-and-beta-channel.html",
    "http://osvdb.org/80740",
    "http://secunia.com/advisories/48618",
    "http://secunia.com/advisories/48691",
    "http://secunia.com/advisories/48763",
    "http://secunia.com/advisories/48972",
    "http://secunia.com/advisories/49047",
    "http://secunia.com/advisories/49055",
    "http://www.mandriva.com/security/advisories?name=MDVSA-2012:066",
    "http://www.mandriva.com/security/advisories?name=MDVSA-2012:081",
    "http://www.mozilla.org/security/announce/2012/mfsa2012-31.html",
    "http://www.securitytracker.com/id?1026877",
    "https://bugzilla.mozilla.org/show_bug.cgi?id=739925",
    "https://exchange.xforce.ibmcloud.com/vulnerabilities/74412",
    "https://oval.cisecurity.org/repository/search/definition/oval%3Aorg.mitre.oval%3Adef%3A15488",
    "https://github.com/CVEProject/cvelistV5/blob/04cbba20eadf072d0c2a69a2764987d5116b9b8d/cves/2011/3xxx/CVE-2011-3062.json",
    "https://github.com/LiuCan01/cve-list-pro/blob/78b55511cee3604c22d518e32822f0435d0cacc0/cve-list/CVE-2011/CVE-2011-3062",
    "https://github.com/nottrobin/ubuntu-cve-tracker/blob/36e411296b5707284049ec2e0db8d2622feca498/retired/CVE-2011-3062",
    "https://github.com/Patrowl/PatrowlHearsData/blob/a4bac3f294639f471e4ce83e9756b93968e8a651/CVE/data/2011/CVE-2011-3062.json",
    "https://github.com/neuvector/vul-source/blob/e03c5655bebd4c9a948dcb1b37e1e76b72295ca6/ubuntu-cve-tracker/retired/CVE-2011-3062",
    "https://github.com/opencve/opencve-kb/blob/45ecaf1c383359875291f7e283d2034bac2094e4/2011/CVE-2011-3062.json",
    "https://github.com/nomi-sec/NVD-Database/blob/23dc120c34402aaa65883c51c1d03b3cb02c20cb/2011/CVE-2011-3062.json",
    "https://github.com/VulnerabilityHistoryProject/chromium-vulnerabilities/blob/777486cd3fbe37797200e30f01e0397b40338964/cves/CVE-2011-3062.yml",
    "https://github.com/eslerm/ubuntu-cve-tracker/blob/f17e5ebf7a87347cc68d8fae347d07409a857342/retired/CVE-2011-3062",
    "https://github.com/olbat/nvdcve/blob/add906b6a8ba20fd533c6fdd7f023c73e6090f3a/nvdcve/CVE-2011-3062.json",
]
