[info]
author = "ave"
description = "检测 Cobalt RaQ 2.0/RaQ 3i 服务器上是否存在存在权限绕过漏洞的 cgiwrap 程序。通过请求 /cgiwrap 路径判断 cgiwrap 是否被安装，若返回 200 则表明目标运行存在漏洞的 cgiwrap 版本，恶意站点管理员可越权访问其他虚拟站点的数据。"
id = "POC-AVE-1999-1164"
name = "Cobalt RaQ cgiwrap 权限绕过漏洞 PoC"
severity = "high"
tags = ["ave-1999-1164"]
vuln_id = [
    "CVE-1999-1530",
    "AVE-1999-1164",
]

[poc]
logic = "any"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/cgiwrap"
protocol = "http"

[[poc.requests.matchers]]
expect = true
part = "body"
status = [200]
type = "status"
