[info]
author = "ave"
description = "SGI IRIX midikeys 程序在调用文本编辑器处理文件时未充分限制文件路径，本地用户可利用该缺陷修改系统任意文件（如 /etc/passwd 或 crontab），从而提升至 root 权限。本 PoC 通过 file 协议检测目标系统是否存在可被 midikeys 修改的高权限文件作为存在性佐证。"
id = "POC-AVE-1999-0686"
name = "CVE-1999-0765 SGI IRIX midikeys 本地任意文件修改 PoC"
severity = "critical"
tags = ["ave-1999-0686"]
vuln_id = [
    "CVE-1999-0765",
    "AVE-1999-0686",
]

[poc]
logic = "all"

[[poc.requests]]
path = "/etc/passwd"
protocol = "file"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = ["root:"]
