[info]
author = "ave"
description = "SCO UnixWare 7.x 部分程序崩溃时会以可预测文件名 ./core.pid 写入核心转储文件。本地用户可预先将 ./core.pid 符号链接至敏感文件，触发目标程序崩溃后通过该链接覆盖被指向文件，造成本地文件篡改或权限提升。此 PoC 验证当前目录可被创建 core.pid 符号链接并指向受控文件，复现漏洞利用前提条件。"
id = "POC-AVE-1999-0664"
name = "CVE-1999-0864 PoC"
severity = "high"
tags = ["ave-1999-0664"]
vuln_id = [
    "CVE-1999-0864",
    "AVE-1999-0664",
]

[poc]
logic = "all"

[[poc.requests]]
path = "./core.pid"
protocol = "file"

[[poc.requests.matchers]]
expect = false
part = "body"
type = "word"
words = ["core.pid"]
