[info]
author = "ave"
description = "通过 HTTP 服务提供包含 ImportExportFavorites ActiveX 控件的恶意 HTML 页面，验证 Microsoft Internet Explorer 4.x/5.x 的导入/导出收藏夹功能存在的远程代码执行漏洞"
id = "POC-AVE-1999-0309"
name = "Microsoft Internet Explorer ImportExportFavorites RCE PoC"
severity = "high"
tags = [
    "ave-1999-0309",
    "cve-1999-0702",
]
vuln_id = [
    "CVE-1999-0702",
    "AVE-1999-0309",
]

[poc]
logic = "all"

[[poc.requests]]
method = "GET"
path = "/{{BaseURL}}/exploit.html"
protocol = "http"

[poc.requests.body]
content = ""
type = "raw"

[[poc.requests.matchers]]
expect = true
part = "body"
type = "word"
words = ["ImportExportFavorites"]
