[basic]
description = 'DotNetNuke (DNN) 内容管理系统在处理 Cookie 数据时存在代码注入漏洞，攻击者可通过精心构造的 Cookie 负载向服务器注入恶意代码。由于攻击者无需身份验证且无需用户交互即可触发漏洞，导致攻击者在受影响的 DNN 网站上拥有了远程代码执行权限。该漏洞影响版本早于 9.1.1 的所有 DNN 系统，攻击者可利用此漏洞获取目标服务器控制权、窃取敏感数据或进一步横向移动到内部网络。该漏洞因其严重性而被评为 "2017-08 (Critical) Possible remote code execution on DNN sites."，CVSS 评分高达 8.8，威胁等级为 HIGH。'
published = "2017-07-20T12:29:00Z"
remediation = "立即升级 DotNetNuke (DNN) 至 9.1.1 或更高版本（官方安全更新已修复该 Cookie 反序列化 RCE 漏洞）。若暂时无法升级，可在 WAF 层面拦截包含恶意序列化载荷的 Cookie 请求，并限制管理后台仅允许受信 IP 访问作为临时缓解措施。"
score = 8.8
severity = "HIGH"
sources = ["nuclei"]
title = "DNN DotNetNuke 远程代码执行漏洞"
updated = "2026-06-17T01:28:59Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2017-9822"]
ave_id = "AVE-2017-1308"

[meta]
collected_at = "2026-07-29T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://packetstormsecurity.com/files/157080/DotNetNuke-Cookie-Deserialization-Remote-Code-Execution.html",
    "http://www.dnnsoftware.com/community/security/security-center",
    "http://www.securityfocus.com/bid/102213",
    "https://www.cisa.gov/known-exploited-vulnerabilities-catalog?field_cve=CVE-2017-9822",
    "https://github.com/projectdiscovery/nuclei-templates/blob/main/http/cves/2017/CVE-2017-9822.yaml",
    "https://github.com/trickest/cve/blob/b3a270a001a31742516eaea5c494f365de9d3c80/2017/CVE-2017-9822.md",
    "https://github.com/0xMarcio/cve/blob/467e8414b7cae9064886839b1c4a1f4c155804ed/2017/CVE-2017-9822.md",
    "https://github.com/nomi-sec/PoC-in-GitHub/blob/ae7cbf60471587bdea4445c1578df6c016019acf/2017/CVE-2017-9822.json",
    "https://github.com/ExpLangcn/NucleiTP/blob/2b7ecb9031a6eda4f272793045f29b339d8e0cce/CVES/high/CVE-2017-9822.yaml",
    "https://github.com/cckuailong/reapoc/blob/699762e4c31d0183733f64313d8fc3be6470bd37/2017/CVE-2017-9822/poc/pocsploit/CVE-2017-9822.py",
    "https://github.com/cckuailong/pocsploit/blob/fe4a3154e59d2bebd55ccfdf62f4f7efb21b5a2a/modules/cves/2017/CVE-2017-9822.py",
    "https://github.com/arschlochnop/VulnWatchdog/blob/bed1b4e1019005da7f44bc035aba33656b38496b/data/by-cve/CVE-2017-9822.md",
    "https://github.com/sari3l/Poc-Monitor/blob/e2167826924a909ba74aa4b927b955e7dace62c3/2017/CVE-2017-9822.json",
    "https://github.com/arschlochnop/VulnWatchdog/blob/bed1b4e1019005da7f44bc035aba33656b38496b/data/2017/CVE-2017-9822-Tnot123_cve-2017-9822.md",
    "https://github.com/Ostorlab/KEV/blob/8feadeb8b7ff54359eab87941769781629146b23/nuclei/CVE-2017-9822.yaml",
    "https://github.com/murataydemir/CVE-2017-9822",
    "https://github.com/tranphuc2005/CVE-2017-9822",
    "https://github.com/Tnot123/cve-2017-9822",
]
