[basic]
description = "WordPress 4.9.1 之前版本中的 wp-includes/functions.php 文件未对 .js 文件上传要求 unfiltered_html 权限，导致拥有订阅者及以上权限的认证用户可上传包含恶意 JavaScript 代码的 .js 文件。当其他用户访问包含该恶意文件的页面时，脚本将在浏览器中执行，造成存储型跨站脚本攻击（XSS）。攻击者需拥有 WordPress 站点的最低级账号权限，且需诱使管理员或普通用户访问受影响页面。该漏洞影响 WordPress 4.8.3 及更早版本，CVSS 评分 5.4，危害等级中危。"
published = "2017-12-02T06:29:00Z"
remediation = "升级 WordPress 至 4.9.1 或更高版本，该版本要求上传 .js 文件时具备 unfiltered_html 权限，从而修复跨站脚本攻击。如无法立即升级，可限制低权限用户上传 JavaScript 文件作为临时缓解措施。"
score = 5.4
severity = "MEDIUM"
sources = ["nuclei"]
title = "WordPress WordPress 跨站脚本漏洞"
updated = "2026-06-17T01:10:19Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2017-17092"]
ave_id = "AVE-2017-0059"

[meta]
collected_at = "2026-07-27T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://www.securityfocus.com/bid/102024",
    "https://codex.wordpress.org/Version_4.9.1",
    "https://github.com/WordPress/WordPress/commit/67d03a98c2cae5f41843c897f206adde299b0509",
    "https://lists.debian.org/debian-lts-announce/2017/12/msg00019.html",
    "https://wordpress.org/news/2017/11/wordpress-4-9-1-security-and-maintenance-release/",
    "https://wpvulndb.com/vulnerabilities/8966",
    "https://www.debian.org/security/2018/dsa-4090",
    "https://github.com/projectdiscovery/nuclei-templates/blob/main/http/cves/2017/CVE-2017-17092.yaml",
    "https://github.com/trickest/cve/blob/be44b05b9428dc18bc0705cf60dd8d8640cd49b1/2017/CVE-2017-17092.md",
    "https://github.com/projectdiscovery/nuclei-templates/blob/4924c84cac6ce9772babf48587bed8df9d0040d0/http/cves/2017/CVE-2017-17092.yaml",
    "https://github.com/CVEProject/cvelistV5/blob/487ea3f21ed49470634e758e1f8f2ac74b64d6b0/cves/2017/17xxx/CVE-2017-17092.json",
    "https://github.com/CVEDB/Poc-Git/blob/0275aeb329b0747c9a1d46160c921eae06095557/2017/CVE-2017-17092.md",
    "https://github.com/linuxadi/40k-nuclei-templates/blob/542be6820c801c02a33aee60f1c05ca7b0b5005f/aditya/folder4/CVE-2017-17092.yaml",
    "https://github.com/topscoder/nuclei-wordfence-cve/blob/bdcc854494aa2f43778044680cffe9dd4de3de0e/nuclei-templates/2017/CVE-2017-17092-wordpress-e5252b2f-c1a1-4fec-abaf-ad234affdcfb.yaml",
    "https://github.com/Akokonunes/Private-Nuclei-Templates/blob/f92d2274458a958ed01345915693cf1dbe026f83/Wordpress/2017/CVE-2017-17092.yaml",
    "https://github.com/LiuCan01/cve-list-pro/blob/78b55511cee3604c22d518e32822f0435d0cacc0/cve-list/CVE-2017/CVE-2017-17092",
    "https://github.com/ARPSyndicate/suricata-vedas/blob/fe24794ad36564b5bbc7c69101525011387b8650/2017/CVE-2017-17092.rules",
    "https://github.com/canonical/ubuntu-security-notices/blob/2a2183b97032e27dffc48e0c05258a59a58abd74/osv/cve/2017/UBUNTU-CVE-2017-17092.json",
]
