[basic]
description = "tags.<value>BeOS 4.5 和 5.0 版本中存在无效系统调用漏洞，本地攻击者可通过构造畸形的直接系统调用并利用中断 37 触发异常，导致系统服务崩溃或拒绝服务。该漏洞影响 BeOS 4.5 和 5.0 版本，攻击者需具有本地访问权限才能利用此漏洞。成功利用后，系统将无法正常运行，造成服务中断，用户应升级到修复版本以消除风险。"
published = "2000-04-10T04:00:00.000"
remediation = "建议将受影响的 BeOS 系统升级至 Be 官方发布的修复版本（BeOS 5.0.3 或后续补丁），以消除中断 37 的畸形系统调用处理缺陷。若暂无法升级，应限制普通本地用户权限、禁止非授权用户登录系统控制台，并通过移除或限制对内核直接系统调用接口的访问作为临时缓解措施，避免本地用户触发拒绝服务。"
score = 2.1
severity = "LOW"
sources = ["cve"]
title = "Be BeOS 4.5/5.0 无效系统调用拒绝服务漏洞"
updated = "2026-06-16T21:51:22.743"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2000-0276"]
ave_id = "AVE-2000-0246"

[meta]
collected_at = "2026-07-19T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://www.securityfocus.com/bid/1098",
    "http://www.securityfocus.com/templates/archive.pike?list=1&msg=20000410131628.659.qmail%40securityfocus.com",
    "https://www.exploit-db.com/exploits/19840",
    "https://github.com/CVEProject/cvelistV5/blob/2aa0c2dcb1730150467a1bc57cd9b2ece96310af/cves/2000/0xxx/CVE-2000-0276.json",
    "https://github.com/LiuCan01/cve-list-pro/blob/78b55511cee3604c22d518e32822f0435d0cacc0/cve-list/CVE-2000/CVE-2000-0276",
    "https://github.com/yarencheng/cve-devops-playground/blob/1fe9b156eeeb72b8f8baa50bbe7bc0d9806e8c64/content/CVE-2000-0276.md",
    "https://github.com/Patrowl/PatrowlHearsData/blob/419b5e73717835e3c91c8f5fe969933e4b2e142e/CVE/data/2000/CVE-2000-0276.json",
    "https://github.com/github/advisory-database/blob/ce77465efdf58fc31a7a0bc8c83705be48abcedf/advisories/unreviewed/2022/04/GHSA-wwrg-82fc-4xc8/GHSA-wwrg-82fc-4xc8.json",
    "https://github.com/intSpLoiT/intframework/blob/eabaa799d0260aa52b735fa9769266d1ce4b64ef/modules/cve_list.txt",
    "https://github.com/olbat/nvdcve/blob/63d4031680b3d3fa77b826660a1e30ffc70ff5cd/nvdcve/CVE-2000-0276.json",
    "https://github.com/KTZgraph/sarenka/blob/f1fb931ab722d6c096d581ed6e3c5966d799fbaa/sarenka/feeds/cve_details/cve_all_details_152300_152400.json",
    "https://github.com/andreafioraldi/ToolsForCyberChallenge/blob/197d3dfd204cf1b9d1af1451455c8831c3ff9948/generated/files_0.list.dict",
    "https://github.com/nomi-sec/CVE-Easy-List/blob/b00846651d73ce227da89de12b15251a83e2ba27/2000.tsv",
]
