[basic]
description = "NTMail 5.x 存在安全绕过漏洞，网络用户可通过将请求重定向至 NTMail 的 Web 配置服务器，绕过代理限制规则。攻击者无需身份认证即可远程利用该漏洞，通过网络访问即可实施攻击，利用复杂度低。该漏洞仅影响系统完整性，不涉及机密性和可用性，CVSS 评分 5.0，危害等级中危。受影响版本为 NTMail 5.x 系列。"
published = "2000-05-11T04:00:00.000"
remediation = "NTMail 5.x 已停止维护，建议立即升级至 Gordano 后续受支持版本或迁移至其他受支持的邮件服务器产品。如无法升级，可在防火墙上限制对 NTMail Web 配置服务端口（默认 80/443）的访问，仅允许受信任管理 IP 连接，并配置代理规则严格过滤重定向请求。"
score = 5
severity = "MEDIUM"
sources = ["avd"]
title = "NTMail 5.x 代理限制绕过漏洞"
updated = "2026-06-16T21:51:40.200"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2000-0416"]
ave_id = "AVE-2000-0449"

[meta]
collected_at = "2026-07-23T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://www.gordano.com/support/archives/ntmail/2000-05/00001114.htm",
    "http://www.securityfocus.com/bid/1196",
    "http://www.securityfocus.com/templates/archive.pike?list=1&msg=NABBJLKKPKIHDIMKFKGCMEFANMAB.georger%40nls.net",
    "https://github.com/CVEProject/cvelistV5/blob/2ee9e77ceac534c670c42073c99286dbb69e9733/cves/2000/0xxx/CVE-2000-0416.json",
    "https://github.com/LiuCan01/cve-list-pro/blob/78b55511cee3604c22d518e32822f0435d0cacc0/cve-list/CVE-2000/CVE-2000-0416",
    "https://github.com/yarencheng/cve-devops-playground/blob/4731f60845c8f35e2bdb03d333a9e9d84c7b1c27/content/CVE-2000-0416.md",
    "https://github.com/Patrowl/PatrowlHearsData/blob/c872795777255e25a47f155fd6d323c05ea13ab9/CVE/data/2000/CVE-2000-0416.json",
    "https://github.com/github/advisory-database/blob/daf3a08cbe0139b666db9d48681b6efcebbecad5/advisories/unreviewed/2022/04/GHSA-34f7-g82v-435m/GHSA-34f7-g82v-435m.json",
    "https://github.com/intSpLoiT/intframework/blob/eabaa799d0260aa52b735fa9769266d1ce4b64ef/modules/cve_list.txt",
    "https://github.com/olbat/nvdcve/blob/5b92f5917a4a825187ccaac594f43456a77ea8f3/nvdcve/CVE-2000-0416.json",
    "https://github.com/KTZgraph/sarenka/blob/f1fb931ab722d6c096d581ed6e3c5966d799fbaa/sarenka/feeds/cve_details/cve_all_details_152400_152500.json",
    "https://github.com/Yuning-J/VulnerabilityClassifier/blob/c0f06c21b73c26b5ee2b75c21a498eb04eada4b5/threatPrediction/cveIDThreatType/cve_idbypass",
    "https://github.com/nomi-sec/CVE-Easy-List/blob/8b2b9a8673bea39f5c895cdb2f43d026330c1de0/2000.tsv",
]
