[basic]
description = "BB4 Big Brother Network Monitor 1.5d3 之前的多个 CGI 脚本（包括 bb-hist.sh、bb-histlog.sh、bb-hostsvc.sh、bb-rep.sh、bb-replog.sh 及 bb-ack.sh）存在信息泄露漏洞。远程攻击者可通过在 HISTFILE 参数中指定目标文件路径，根据服务器返回的错误信息差异判断文件或用户 ID 是否存在，从而获取系统敏感信息。该漏洞无需身份认证即可利用，影响所有暴露 BB Web 接口的系统。"
published = "2001-01-09T05:00:00Z"
remediation = "升级 Big Brother 到 1.5d3 或更高版本，修复所有受影响脚本（bb-hist.sh、bb-histlog.sh、bb-hostsvc.sh、bb-rep.sh、bb-replog.sh、bb-ack.sh）中 HISTFILE 参数的输入验证漏洞。如暂无法升级，应在 Web 服务器前端对包含 HISTFILE 参数的请求进行过滤，并限制对 bb-*.sh 脚本的远程访问权限，仅允许受信 IP 访问。"
score = 5
severity = "MEDIUM"
sources = ["avd"]
title = "BB4 Big Brother Network Monitor 文件存在性信息泄露漏洞"
updated = "2026-06-16T21:53:19Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2000-1177"]
ave_id = "AVE-2000-0833"

[meta]
collected_at = "2026-08-07T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://archives.neohapsis.com/archives/bugtraq/2000-11/0284.html",
    "http://bb4.com/incident.nov21",
    "http://www.securityfocus.com/bid/1971",
    "https://www.exploit-db.com/exploits/20413",
    "https://github.com/CVEProject/cvelistV5/blob/218bad847444129ddbebfeea62eb92fdb08e16d7/cves/2000/1xxx/CVE-2000-1177.json",
    "https://github.com/Patrowl/PatrowlHearsData/blob/24fd852826426077fab5deff7dee8e1c33b7de89/CVE/data/2000/CVE-2000-1177.json",
    "https://github.com/LiuCan01/cve-list-pro/blob/78b55511cee3604c22d518e32822f0435d0cacc0/cve-list/CVE-2000/CVE-2000-1177",
    "https://github.com/nomi-sec/NVD-Database/blob/23dc120c34402aaa65883c51c1d03b3cb02c20cb/2000/CVE-2000-1177.json",
    "https://github.com/olbat/nvdcve/blob/7bc9b867d9432dd98ba48c5f757dc43b5388968a/nvdcve/CVE-2000-1177.json",
    "https://github.com/opencve/opencve-kb/blob/5bbd99d97db717bad32ae459bda1c65e7b37a2b4/2000/CVE-2000-1177.json",
    "https://github.com/fkie-cad/nvd-json-data-feeds/blob/63a532b725792b89ea32ae40fb744f9c8a9ba2df/CVE-2000/CVE-2000-11xx/CVE-2000-1177.json",
    "https://github.com/HORKimhab/poc-cve-collection/blob/1942bcdb9701d268432416f93669c664bcd7b212/2000/1xxx/CVE-2000-1177.md",
    "https://github.com/CyberSecAI/cve_info/blob/03b7e36424574a3a9ba5fd13480a326b666a1046/2000/1xxx/CVE-2000-1177.json",
    "https://github.com/CVEProject/cvelist-dev/blob/5b8fbb570438e8094550205589cc6f1d122acc94/2000/1xxx/CVE-2000-1177.json",
]
