[basic]
description = "screen 3.9.5 及更早版本中存在格式化字符串漏洞，由于程序在处理 vbell_msg 初始化变量时未对用户提供的格式字符进行过滤，本地攻击者可通过向该变量传递特制的格式化字符串触发此漏洞，导致内存越界读写，从而获取 root 权限。此漏洞需要攻击者拥有本地访问权限，影响运行 screen 3.9.5 及之前版本的系统。"
published = "2000-12-19T05:00:00.000"
remediation = "立即升级 GNU Screen 至 3.9.5-8 或更高版本（各发行版已发布对应补丁：Red Hat 用户安装 RHSA-2000:058 更新、FreeBSD 用户应用 FreeBSD-SA-00:46 补丁、Mandrake 用户安装 MDKSA-2000:044 更新）。如使用现代发行版，确保 screen 版本不低于 4.0.0。同时不要将不可信用户输入传递给 vbell_msg 等格式化字符串参数，避免触发格式字符串漏洞。"
score = 4.6
severity = "MEDIUM"
sources = ["exploitdb"]
title = "Juergen Weigert screen 格式化字符串漏洞"
updated = "2026-06-16T21:52:43.420"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2000-0901"]
ave_id = "AVE-2000-0655"

[meta]
collected_at = "2026-07-21T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://archives.neohapsis.com/archives/bugtraq/2000-08/0530.html",
    "http://www.linux-mandrake.com/en/updates/MDKSA-2000-044.php3",
    "http://www.novell.com/linux/security/advisories/adv6_draht_screen_txt.html",
    "http://www.redhat.com/support/errata/RHSA-2000-058.html",
    "http://www.securityfocus.com/archive/1/80178",
    "http://www.securityfocus.com/bid/1641",
    "https://exchange.xforce.ibmcloud.com/vulnerabilities/5188",
    "https://www.exploit-db.com/exploits/20191",
    "https://github.com/CVEProject/cvelistV5/blob/4f761f58350f835cb02025d033f6f8c7f536e6b7/cves/2000/0xxx/CVE-2000-0901.json",
    "https://github.com/LiuCan01/cve-list-pro/blob/78b55511cee3604c22d518e32822f0435d0cacc0/cve-list/CVE-2000/CVE-2000-0901",
    "https://github.com/yarencheng/cve-devops-playground/blob/7f1c35ad28226319c149c937b6a2e7a1986924ce/content/CVE-2000-0901.md",
    "https://github.com/Patrowl/PatrowlHearsData/blob/2658816172d77941b1080be8784997934e564ee9/CVE/data/2000/CVE-2000-0901.json",
    "https://github.com/github/advisory-database/blob/26d7afd7aa97d50454756aec5636fa553464ffd2/advisories/unreviewed/2022/05/GHSA-rvv8-fhqp-59jg/GHSA-rvv8-fhqp-59jg.json",
    "https://github.com/intSpLoiT/intframework/blob/eabaa799d0260aa52b735fa9769266d1ce4b64ef/modules/cve_list.txt",
    "https://github.com/nomi-sec/NVD-Database/blob/23dc120c34402aaa65883c51c1d03b3cb02c20cb/2000/CVE-2000-0901.json",
    "https://github.com/andreafioraldi/ToolsForCyberChallenge/blob/197d3dfd204cf1b9d1af1451455c8831c3ff9948/generated/files_2.list.dict",
    "https://github.com/oasis-open/cti-stix-common-objects/blob/55ba7598cbd5a52577b6887871505d931d85cb61/objects/vulnerability/vulnerability--ee2694b3-778f-47b3-9996-dbd0b430be41.json",
    "https://github.com/debiancn/debian.org/blob/6abc98daa6356b20e410013a6920b3764af682d4/english/security/2000/20000902a.data",
]
