[basic]
description = "NAI Net Tools PKI Server 1.0 的 strong.exe 程序中存在格式字符串漏洞。远程攻击者可通过向目标服务器发送一个包含特制格式字符串且后缀为 .XUDA 的 URL 请求，触发程序在处理请求时的解析缺陷。该漏洞允许未经身份验证的攻击者在远程服务器上执行任意代码，导致系统完全被接管。此漏洞影响 HotFix 3 之前的所有 1.0 版本。"
published = "2000-10-20T04:00:00Z"
remediation = "建议立即安装 NAI Net Tools PKI Server 1.0 的 HotFix 3 补丁。若无法立即升级，建议在 Web 服务器或防火墙层面拦截所有包含 .XUDA 扩展名的请求，以防止远程攻击者利用格式字符串漏洞执行任意代码。"
score = 7.5
severity = "HIGH"
sources = ["avd"]
title = "NAI Net Tools PKI Server 1.0 格式字符串远程代码执行漏洞"
updated = "2026-06-16T21:52:23Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2000-0741"]
ave_id = "AVE-2000-0571"

[meta]
collected_at = "2026-07-29T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://archives.neohapsis.com/archives/bugtraq/2000-07/0473.html",
    "http://download.nai.com/products/licensed/pgp/hf3pki10.txt",
    "http://www.osvdb.org/1490",
    "http://www.securityfocus.com/bid/1538",
    "https://www.exploit-db.com/exploits/20136",
    "https://github.com/CVEProject/cvelistV5/blob/33ec434954e61bc39d0dce97d60b798545efd141/cves/2000/0xxx/CVE-2000-0741.json",
    "https://github.com/Patrowl/PatrowlHearsData/blob/39cf4547de2e266ceb8827aa7ae993ba929a25b6/CVE/data/2000/CVE-2000-0741.json",
    "https://github.com/LiuCan01/cve-list-pro/blob/78b55511cee3604c22d518e32822f0435d0cacc0/cve-list/CVE-2000/CVE-2000-0741",
    "https://github.com/nomi-sec/NVD-Database/blob/23dc120c34402aaa65883c51c1d03b3cb02c20cb/2000/CVE-2000-0741.json",
    "https://github.com/opencve/opencve-kb/blob/2d3362e5d3b95223fab83ca531e4c3b2a7ca274a/2000/CVE-2000-0741.json",
    "https://github.com/olbat/nvdcve/blob/add906b6a8ba20fd533c6fdd7f023c73e6090f3a/nvdcve/CVE-2000-0741.json",
    "https://github.com/HORKimhab/poc-cve-collection/blob/63bc6ccb7d9e7d0447e23eb842c0b23beddd261c/2000/0xxx/CVE-2000-0741.md",
    "https://github.com/fkie-cad/nvd-json-data-feeds/blob/1b01d01b655cac08088621898fd70278524e2f0e/CVE-2000/CVE-2000-07xx/CVE-2000-0741.json",
    "https://github.com/CyberSecAI/cve_info/blob/03b7e36424574a3a9ba5fd13480a326b666a1046/2000/0xxx/CVE-2000-0741.json",
    "https://github.com/CVEProject/cvelist-dev/blob/5b8fbb570438e8094550205589cc6f1d122acc94/2000/0xxx/CVE-2000-0741.json",
]
