[basic]
description = "通达 通达OA前台反序列化漏洞 反序列化 - 08.08"
published = ""
remediation = "请参考官方安全公告，及时安装安全更新或升级到最新版本。"
score = 5
severity = "MEDIUM"
sources = ["hwpoc"]
title = "通达OA前台反序列化漏洞"
updated = ""

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["HWPOC-2023-05e721a2"]
ave_id = "AVE-2023-0325"

[meta]
collected_at = "2026-07-17T07:12:51.599530917+00:00"
status = "completed"

[references]
urls = []
