[basic]
description = "Cisco 交换机与路由器运行 IOS 12.1 及更早版本时，其 TCP 初始序列号（ISN）生成算法存在可预测缺陷，远程攻击者无需身份认证即可预测 ISN 值，进而伪造或劫持目标设备的 TCP 连接，实施会话劫持、数据窃听或恶意数据注入攻击。该漏洞影响所有运行受影响 IOS 版本的 Cisco 网络设备，攻击条件宽松，可利用性高，CVSS 评分 7.5，危害等级为 HIGH。"
published = "2001-05-03T04:00:00Z"
remediation = "升级 Cisco IOS 至 12.1(5) 或更高版本（如 12.1(9)E、12.2 等已修复版本）。若暂无法升级，可在边界防火墙配置 ACL 限制非信任源访问 TCP 服务端口，并启用 TCP 序列号随机化功能（如支持）作为临时缓解措施。"
score = 7.5
severity = "HIGH"
sources = ["cve"]
title = "思科 IOS TCP 初始序列号可预测欺骗漏洞"
updated = "2026-06-16T21:54:02Z"

[exploit]
exp_urls = []
poc_urls = []

[id]
aliases = ["CVE-2001-0288"]
ave_id = "AVE-2001-1309"

[meta]
collected_at = "2026-08-07T00:00:00Z"
status = "completed"

[references]
urls = [
    "http://www.cisco.com/warp/public/707/ios-tcp-isn-random-pub.shtml",
    "https://github.com/trickest/cve/blob/8c4eb2837c857f4cda9b4ed4ab227a0668647438/2001/CVE-2001-0288.md",
    "https://github.com/CVEProject/cvelistV5/blob/e089fbede0f95f2d4df85cd26008124a09d73dc8/cves/2001/0xxx/CVE-2001-0288.json",
    "https://github.com/Patrowl/PatrowlHearsData/blob/9cadf2781966b46cf2833362970d0629a97c0767/CVE/data/2001/CVE-2001-0288.json",
    "https://github.com/LiuCan01/cve-list-pro/blob/78b55511cee3604c22d518e32822f0435d0cacc0/cve-list/CVE-2001/CVE-2001-0288",
    "https://github.com/nomi-sec/NVD-Database/blob/23dc120c34402aaa65883c51c1d03b3cb02c20cb/2001/CVE-2001-0288.json",
    "https://github.com/olbat/nvdcve/blob/7bc9b867d9432dd98ba48c5f757dc43b5388968a/nvdcve/CVE-2001-0288.json",
    "https://github.com/mabitoski/cve_submodules/blob/44ad7e2705b3aef1b2ffaf64bd47596c10a6c2e4/2001/CVE-2001-0288.md",
    "https://github.com/fkie-cad/nvd-json-data-feeds/blob/2dd45b48e0efa0fde64742f95da829dc45ea506c/CVE-2001/CVE-2001-02xx/CVE-2001-0288.json",
    "https://github.com/brenonevs/prs-pentest/blob/001cf17eedeb4aad73618d3140ca1f5dc93e69b3/CVEs & POCs/2001/CVE-2001-0288.md",
    "https://github.com/opencve/opencve-kb/blob/db96875ac5ac7d5604926ae5714d3a05b58a674d/2001/CVE-2001-0288.json",
]
